### ISSUE TITLE
Add support for default values

### ISSUE THREAD

**Issue by watzon** [Crecto/crecto#128]
It would be nice to have a `default` option in the schema

**Comment by fridgerator** [comment]
I've thought about this as well, the issue is I'm not sure how to go about it.  The only way I can think of doing it is to set the default values in an `initialize` method.  However if this method gets overwritten in the class, which happens frequently, the default values wont work.  It would be great if there were an `after_initialization` macro, but there isn't.

Let me know if you have any ideas.

**Comment by watzon** [comment]
That is a very good point. I didn't think about that. I'll be sure to let you know if I come up with anything

**Comment by faultyserver** [comment]
Some quick thoughts:

Both `DB.mapping` and `JSON.mapping` support `default` keys for their fields, which are added to the initializers that those methods create.

Like you said, overriding the initializer would eliminate the default value.....BUT, you could use the "Catch-all initialization" syntax to work around that. Consider this example:


```crystal
class Thing
  # For simplicity, in this example, I'm not using `property`
  # but that would also work the same way.
  @a = 123

  def initialize
  end

  def a
    @a
  end
end

Thing.new.a #=> 123
```

So `@a` does _not_ get initialized by the user-defined initializer, but the value of `@a` is still set to 123. The semantics for this are explained at the bottom of the [Methods and instance variables documentation](https://crystal-lang.org/docs/syntax_and_semantics/methods_and_instance_variables.html).

**Comment by watzon** [comment]
@faultyserver I like it

**Comment by fridgerator** [comment]
@faultyserver oh wow, seems so obvious now that you pointed that out

**Comment by fridgerator** [comment]
easier than I thought #129
