### ISSUE TITLE
Manually specify Column for foreign key

### ISSUE THREAD

**Issue by zbaylin** [Crecto/crecto#159]
A schema defined as such will always try to match a User id to the column user_id.
```
class Group < Crecto::Model
    schema "groups" do
      belongs_to :user, User
      field :title, String
      field :school_code, String,
        default: Random::Secure.urlsafe_base64(6)
      field :expiration_date, Time,
        default: Time.now + 1.year
    end
  end
```

However, I would like it to be matched to the column group_owner.

I can't seem to find if this is currently possible. Any help would be greatly appreciated.

**Comment by zbaylin** [comment]
If I do it this way, then try to do `group.group_owner = user`, it raises an exception saying there is no Group attribute called `group_owner`

**Comment by fridgerator** [comment]
is the column name `group_owner_id`, or just `group_owner` ?

**Comment by zbaylin** [comment]
just `group_owner`. I can change it to `group_owner_id` if I have to.

**Comment by fridgerator** [comment]
The column name shouldn't matter if its being specified with the `foreign_key` field option.

If thats the column name, then you would set it with the user id rather than the user `group.group_owner = user.id`

However if you're getting an error that `group_owner` doesn't exist after setting the option then I'm not sure whats going on, i'll have to mess with it more later when I get time.

**Comment by zbaylin** [comment]
should I specify `group_owner` as a field as well, i.e. `field :group_owner, Int64`?

**Comment by fridgerator** [comment]
yeah try that, I dont remember if the field is automatically created for belongs_to assiciations

**Comment by zbaylin** [comment]
oh your previous comment of assigning it to `user.id` fixed it. Thank you.
