### ISSUE TITLE
Critical: v0.10.0 broke JSON deserialization

### ISSUE THREAD

**Issue by m-o-e** [Crecto/crecto#226]
### Test-case:

```crystal
class MyModel < Crecto::Model
  schema "foo" do
    field :foo, Int32
  end
end
pp MyModel.from_json("{\"foo\": 32768 }").foo
```

With crecto v0.9.0 it prints: `32768`

With crecto v0.10.0 it prints: `-32768_i16` 💣

**Comment by faultyserver** [comment]
Haven't had a chance to run my own tests, but I _think_ this could be the culprit:

https://github.com/Crecto/crecto/blob/813ccdf796b71ebeb156b0bf6611c8eba8042d35/src/types.cr#L8

The `Int8 | Int16` was added in `v0.10.0`, and because [`Int32` and `Int64` are translated to `PkeyValue` in the setup](https://github.com/Crecto/crecto/blob/813ccdf796b71ebeb156b0bf6611c8eba8042d35/src/crecto/schema.cr#L158), I think it's confusing the JSON parser that gets generated. Since `32768` can fit in an `Int16`, it might realize that and just try to compress it for some reason.

Not sure what the fix for this would be, either.
